# Generated by Django 5.2.6 on 2025-10-15 04:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('standard_row_count', models.PositiveIntegerField(default=0)),
                ('vip_row_count', models.PositiveIntegerField(default=0)),
                ('couple_row_count', models.PositiveIntegerField(default=0)),
                ('seats_per_row', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('duration_min', models.PositiveIntegerField()),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'api_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_label', models.CharField(max_length=5)),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('couple', 'Couple')], default='standard', max_length=10)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.auditorium')),
            ],
            options={
                'ordering': ['auditorium', 'row_label', 'seat_number'],
                'unique_together': {('auditorium', 'row_label', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showtimes', to='api.auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showtimes', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qr_code', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('paid', 'Paid'), ('checked_in', 'Checked In'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='reserved', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='api.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.showtime')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
            options={
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_id', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='api_payment_booking_a0e9be_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie'], name='api_showtim_movie_i_043b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['auditorium', 'start_time'], name='api_showtim_auditor_3717c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('auditorium', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='api_booking_user_id_cfdf50_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['showtime'], name='api_booking_showtim_c4c32e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['expires_at'], name='api_booking_expires_651e73_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['showtime'], name='api_ticket_showtim_31e4c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('showtime', 'seat')},
        ),
    ]
