# Generated by Django 5.2.6 on 2025-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('e_wallet', 'E-Wallet'), ('bank_transfer', 'Bank Transfer')], default='credit_card', max_length=40),
        ),
    ]
